version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./storage:/storage
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage


  keycloak:
      image: quay.io/keycloak/keycloak:legacy
      environment:
        DB_VENDOR: ${DB_VENDOR}
        DB_ADDR: ${DB_ADDR}
        DB_DATABASE: ${DB_DATABASE}
        DB_USER: ${DB_USER}
        DB_PASSWORD: ${DB_PASSWORD}
        KEYCLOAK_USER: ${KEYCLOAK_USER}
        KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
        PROXY_ADDRESS_FORWARDING: "true"
        REDIRECT_SOCKET: "proxy-https"
        KEYCLOAK_FRONTEND_URL: https://style-transfer.awsexpress.cloud/auth
      
      command: ["-Djboss.http.port=8081"]

      ports:
        - 8081:8081

  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
    depends_on:
        - frontend
