version: '3'

services:
  frontend:
    build: frontend
    ports:
      - 8501:8501
    depends_on:
      - backend
    volumes:
        - ./storage:/storage
  backend:
    build: backend
    ports:
      - 8080:8080
    volumes:
      - ./storage:/storage

  keycloak:
      image: jboss/keycloak:latest
      environment:
        DB_VENDOR: MYSQL
        DB_ADDR: python-app.c23omn6ex3h0.ap-south-1.rds.amazonaws.com
        DB_DATABASE: keycloak
        DB_USER: admin
        DB_PASSWORD: qDVwXW3VkUnxIVIgNUbg
        KEYCLOAK_USER: admin
        KEYCLOAK_PASSWORD: Pa55w0rd
        PROXY_ADDRESS_FORWARDING: "true"
        REDIRECT_SOCKET: "proxy-https"
        KEYCLOAK_FRONTEND_URL: https://43.205.158.179/auth

      ports:
        - "8081:8081"

  nginx:
    image: nginx
    container_name: nginx
    restart: on-failure
    volumes:
      - ./conf:/etc/nginx/conf.d
      - /usr/local/certs:/etc/nginx/certs
    ports:
      - "80:80"
      - "443:443"
